name: Deploy to AWS
on:
  push:
    branches:
      - main # Kodu main-ə atanda işə düşəcək

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Layihə qovluğuna gir
            cd BookClubProject

            # 2. Ən son kodu GitHub-dan çək
            git pull origin main

            # 3. Köhnə container-ləri dayandır (crash-ların qarşısını alır)
            sudo docker-compose down

            # 4. Docker-i yenidən qaldır (dəyişiklikləri tətbiq et)
            sudo docker-compose up -d --build

            # 4. Artıq yer tutan köhnə "zibil" faylları təmizlə (Serverin dolmasın!)
            sudo docker system prune -f
